<?php

return [
    'allergens' => [
        'Gluten',
        'Crustaceans',
        'Eggs',
        'Fish',
        'Peanuts',
        'Soybeans',
        'Milk',
        'Nuts',
        'Celery',
        'Mustard',
        'Sesame',
        'Sulphur dioxide and sulphites',
        'Lupin',
        'Molluscs',
        'Barley',
        'Rye',
        'Oats',
        'Spelt',
        'Kamut',
        'Wheat',
        'Almonds',
        'Hazelnuts',
        'Walnuts',
        'Cashews',
        'Pecans',
        'Brazil nuts',
        'Pistachios',
        'Macadamia nuts',
        'Pine nuts',
        'Coconut',
        'Chestnuts',
        'Mustard seeds',
        'Saffron',
        'Aniseed',
        'Fennel',
        'Dill',
        'Caraway',
        'Coriander',
        'Fenugreek',
        'Paprika'
    ]
];
